### PR TITLE
Add Favorite checkmark in Session screen

### PR DESCRIPTION
**Pull request by vanniktech**
First time in Kotlin and during the day I didn't get to it. Let me know what you think

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks, looks good.
the problem is that the icon will be displayed also in the "My Schedule screen" ... 
Not sure if this is an issue, what do you think?

**Comment by vanniktech** [comment]
Hmm not really. I'd say it's consistent but if you want I could find a way to remove it.

**Comment by sockeqwe** [comment]
No worries, its already merged !i have used another icon)

Niklas Baudy notifications@github.com schrieb am Do., 16. Juni 2016,
05:52:

**Comment by vanniktech** [comment]
Yup I saw it and also installed it locally since the version is not yet uploaded. Thanks 👍 See you at your talk

**Comment by sockeqwe** [comment]
Yes, I sent the signed apk to someone from droidcon for uploading it in
play store (it s not my play store Account) but it seems that it hasn't
been uploaded yet ... thanks for your pull request, see you there ...

Niklas Baudy notifications@github.com schrieb am Do., 16. Juni 2016,
09:19:

**Comment by friedger** [comment]
Has been published right now.

**Comment by sockeqwe** [comment]
Thanks!

Friedger Müffke notifications@github.com schrieb am Do., 16. Juni 2016,
09:36:

**Pull request merged**
